openapi: 3.0.0
info:
  title: API de Usuários XPTO
  version: 1.0.0
paths:
  /usuarios/{id}:
    get:
      summary: Retorna os detalhes de um usuário
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    example: "123"
                  nome:
                    type: string
                  email:
                    type: string
                  data_cadastro:
                    type: string
                    format: date-time
                  ativo:
                    type: boolean